### ISSUE TITLE
Running pubrunner

### ISSUE THREAD

**Issue by iCHAIT** [jakelever/biowordlists#1]
Hi Jake,

Thanks for this awesome tool. I am interested in using this to create a list of biomarkers. I see that the latest version was created 8 months back and has not been updated since. So I was planning to have the latest word list and plan to run pubrunner.

I have a few questions - 

1. What is the preferred computing resource/configuration for running pubrunner? 
2. How much computing time does it take?

Thanks :)

**Comment by jakelever** [comment]
Hey, for this project, it shouldn't take that long to run and can probably be done on a laptop. I'd guess a few hours to run it on a laptop.

If you want to use PubRunner for other bigger projects (e.g. CIViCmine), then a compute cluster is really needed as a laptop would just take too long to process all of PubMed. But this project doesn't process all of PubMed, so it doesn't take too long.

**Comment by iCHAIT** [comment]
Thanks for the information @jakelever :)
